models.py
from app import db
from datetime import datetime
import re

from flask_security import UserMixin, RoleMixin


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer,
                               db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                     )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    create = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    tags = db.relationship('Tag', secondary=post_tags,
                           backref=db.backref('posts', lazy='dynamic'))

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return f'<Post id: {self.id}, title: {self.title}>'


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return f'{self.name}>'


# Flask Security
roles_users = db.Table('roles_users',
                       db.Column('user_id', db.Integer(),
                                 db.ForeignKey('user.id')),
                       db.Column('role_id', db.Integer(),
                                 db.ForeignKey('role.id'))
                       )


class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users,
                            backref=db.backref('users', lazy='dynamic'))


class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from flask_admin import Admin
from flask_admin import AdminIndexView
from flask_admin.contrib.sqla import ModelView

from flask_security import SQLAlchemyUserDatastore
from flask_security import Security
from flask_security import current_user

from flask import redirect, url_for, request

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

# Admin
from models import *


class AdminMixin:
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url))


class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        model.generate_slug()
        return super(BaseModelView, self).on_model_change(form, model,
                                                          is_created)


class AdminView(AdminMixin, ModelView):
    pass


class HomeAdminView(AdminMixin, AdminIndexView):
    pass


class PostAdminView(AdminMixin, BaseModelView):
    form_columns = ['title', 'body', 'tags']


class TagAdminView(AdminMixin, BaseModelView):
    form_columns = ['name', 'posts']


admin = Admin(app, 'FlaskApp', url='/', index_view=HomeAdminView(name='Home'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))

# Flask-security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

main.py
from app import app
from app import db

from posts.blueprint import posts

import view

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == '__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Post, Tag
from .forms import PostForm

from flask import request
from app import db

from flask import redirect
from flask import url_for

from flask_security import login_required

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Something wrong')

        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))
    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/')
def index():
    q = request.args.get('q')
    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    if q:
        posts = Post.query.filter(
            Post.title.contains(q) | Post.body.contains(q))  # .all()
    else:
        posts = Post.query.order_by(Post.create.desc())
    pages = posts.paginate(page=page, per_page=5)
    return render_template('posts/index.html', posts=posts, pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create new post
{% endblock %}

{% block content_title %}
    New post
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{ url_for('posts.create_post') }}" method="POST">
            {% for field in form %}
            <div class="form-gpoup">
                {{ field.label(class='control-label') }}
                {{ field(class='form-control') }}
            </div>
            {% endfor %}

            <button type="submit" class="btn btn-success">Create</button>

        </form>
    </div>
{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
    Edit post
{% endblock %}

{% block content_title %}
    Edit post
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">
            {% for field in form %}
            <div class="form-gpoup">
                {{ field.label(class='control-label') }}
                {{ field(class='form-control') }}
            </div>
            {% endfor %}

            <button type="submit" class="btn btn-success">Edit</button>

        </form>
    </div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Blueprint index page
{% endblock %}

{% block content_title %}
    Posts
{% endblock %}

{% block content %}
    {% for post in pages.items %}
        <p>
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}"> {{ post.title
                }} </a>
        </p>
    {% endfor %}

    <nav>
        <ul class="pagination">

            <li {% if not pages.has_prev %} class="page-item disabled" {% endif %}>
                <a class="page-link" href="./?page={{ pages.prev_num }}"
                   tabindex="-1" aria-disabled="true">Previous</a>
            </li>

            {% for page in pages.iter_pages() %}
            <li {% if page== pages.page %} class="page-item" {% endif %}><a
                    class="page-link" href="./?page={{ page }}">{{ page }}</a></li>
            {% endfor %}

            <li {% if not pages.has_next %} class="page-item disabled" {% endif %}>
                <a class="page-link" href="./?page={{ pages.next_num }}"
                   tabindex="-1" aria-disabled="true">Next</a>
            </li>
        </ul>
    </nav>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content_title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <div class="'tags">
        {% for tag in tags %}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}"><span class="badge bg-secondary">{{ tag.name }}</span></a>
        {% endfor %}
    </div>

    <div class="main-content">
        {{ post.body }}
   </div>
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }} posts
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}" tag:
{% endblock %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
        </div>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
          crossorigin="anonymous">
    <meta charset="'UTF-8">
    <title>
        {% block title %}
        {% endblock %} | Flask app
    </title>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarTogglerDemo01"
                aria-controls="navbarTogglerDemo01" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="{{ url_for('index') }}">Flask</a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                       href="{{ url_for('posts.index') }}">Blog</a>
                </li>
                <li class="nav-item">
                    {% if current_user.has_role('admin') %}
                        <a class="nav-link active" href="/admin">Admin</a>
                    {% endif %}
                </li>
            </ul>
            <form class="d-flex" method="GET">
                <input class="form-control me-2" type="search"
                       placeholder="Search" aria-label="Search" name="q"
                       value="{{ request.args.get('q', '') }}">
                <button class="btn btn-outline-success" type="submit">Search
                </button>
            </form>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <p></p>
        <p></p>
        <h1>
            {% block content_title %}
            {% endblock %}
        </h1>
        {% block content %}
        {% endblock %}
    </div>
</div>


</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
Index page
{% endblock %}

{% block content_title %}
Main page
{% endblock %}

{% block content %}
<div class="offset-md-3 col-md-6">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque
        lacinia lorem vel metus auctor, eu iaculis eros pretium. Vestibulum
        pellentesque augue nec est maximus, eu efficitur arcu pretium. Lorem
        ipsum dolor sit amet, consectetur adipiscing elit. Phasellus libero
        libero, semper sit amet sapien a, molestie iaculis neque. Maecenas
        tincidunt fringilla augue ac congue. Fusce vulputate tellus sit amet
        felis iaculis sodales. Lorem ipsum dolor sit amet, consectetur
        adipiscing elit.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque
        lacinia lorem vel metus auctor, eu iaculis eros pretium. Vestibulum
        pellentesque augue nec est maximus, eu efficitur arcu pretium. Lorem
        ipsum dolor sit amet, consectetur adipiscing elit. Phasellus libero
        libero, semper sit amet sapien a, molestie iaculis neque. Maecenas
        tincidunt fringilla augue ac congue. Fusce vulputate tellus sit amet
        felis iaculis sodales. Lorem ipsum dolor sit amet, consectetur
        adipiscing elit.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque
        lacinia lorem vel metus auctor, eu iaculis eros pretium. Vestibulum
        pellentesque augue nec est maximus, eu efficitur arcu pretium. Lorem
        ipsum dolor sit amet, consectetur adipiscing elit. Phasellus libero
        libero, semper sit amet sapien a, molestie iaculis neque. Maecenas
        tincidunt fringilla augue ac congue. Fusce vulputate tellus sit amet
        felis iaculis sodales. Lorem ipsum dolor sit amet, consectetur
        adipiscing elit.</p>
</div>
{% endblock %}

templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

templates/security/login_user.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content_title %}
    {{ _('Login') }}
{% endblock %}

{% block content %}
    <div class="offset-md-3 col-md-6">
        {% from "security/_macros.html" import render_field_with_errors, render_field %}
        {% include "security/_messages.html" %}

        <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
          {{ login_user_form.hidden_tag() }}
          {{ render_field_with_errors(login_user_form.email, class='form-control') }}
          {{ render_field_with_errors(login_user_form.password, class='form-control') }}
          {{ render_field_with_errors(login_user_form.remember) }}
          {{ render_field(login_user_form.next) }}
          {{ render_field(login_user_form.submit, class='btn btn-success') }}
        </form>
        {% include "security/_menu.html" %}
    </div>
{% endblock %}